### ISSUE TITLE
[🐛]PIP3 unable to skip platform check in requirement.txt. Feature request: `platform_system`

### ISSUE THREAD

**Issue by gpworkday** [snyk/cli#1102]
- `node -v`: v8.10.0
- `npm -v`: 3.5.2
- `snyk -v`: 1.316.2
- OS: Ubuntu
- Command run: snyk test --command=python3

### Expected behaviour
It should identify vulnerabilities 

### Actual behaviour
Required packages missing: kerberos-sspi

Please run `pip install -r requirements.txt`. If the issue persists try again with --allow-missing.

### Steps to reproduce
>git clone "https://github.com/atlassian-api/atlassian-python-api"
>cd atlassian-python-api
>pip3 install -r requirements.txt
>snyk test --command=python3

--
in requirements.txt there are 2 lines at the bottom
kerberos; platform_system!='Windows'
kerberos-sspi; platform_system=='Windows'

It should skip looking for "kerberos-sspi"

### Debug log
If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.
  snyk test { _: [ [Circular] ], command: 'python3', debug: true } +0ms
  snyk Error running test { error: Error: Required packages missing: kerberos-sspi

Please run `pip install -r requirements.txt`. If the issue persists try again with --allow-missing.
    at Object.<anonymous> (/usr/local/lib/node_modules/snyk/node_modules/snyk-python-plugin/lib/dependencies/inspect-implementation.ts:134:15)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/snyk/node_modules/tslib/tslib.js:111:69)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) } +0ms
Error:
Testing /atlassian-python-api...

Required packages missing: kerberos-sspi

Please run `pip install -r requirements.txt`. If the issue persists try again with --allow-missing.
    at test (/usr/local/lib/node_modules/snyk/src/cli/commands/test/index.ts:233:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  snyk analytics { args:
   [ { command: 'python3',
       debug: true,
       org: undefined,
       showVulnPaths: 'some' } ],
  command: 'bad-command',
  org: undefined,
  metadata:
   { local: true,
     'error-message': '\nTesting /atlassian-python-api...\n\nRequired packages missing: kerberos-sspi\n\nPlease run `pip install -r requirements.txt`. If the issue persists try again with --allow-missing.',
     error: 'Error: \nTesting /atlassian-python-api...\n\nRequired packages missing: kerberos-sspi\n\nPlease run `pip install -r requirements.txt`. If the issue persists try again with --allow-missing.\n    at test (/usr/local/lib/node_modules/snyk/src/cli/commands/test/index.ts:233:19)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
     'error-code': 500,
     command: 'test',
     integrationName: '',
     integrationVersion: '' },
  version: '1.316.2',
  os: 'Linux 4.15',
  nodeVersion: 'v8.10.0',
  id: 'f3bbde43d31903fcfafee52f7dc89e4ab39942ca',
  ci: false,
  durationMs: 451 } +0ms

  snyk Exit code: 2 +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
  snyk request body size: 917 +0ms
  snyk gzipped request body size: 495 +0ms
  snyk not using proxy +0ms

**Comment by lili2311** [comment]
👋 Hi there, are you able to scan you project if you run it with `snyk test --skip-unresolved`?

**Comment by gpworkday** [comment]
That works.

**Comment by lili2311** [comment]
👌 I will update the error message to suggest this and will log in our backlog an improvement to also understand `platform_system` as well as `sys_platform`

**Comment by lili2311** [comment]
Done & done please upgrade the CLI to version `1.320.5` for an enhanced message. Would you like to keep this issue open to track until `platform_system` is supported?

**Comment by gpworkday** [comment]
Thank you. Please keep this issue open till platform_system is fixed.

**Comment by JackuB** [comment]
Closing as it's a stale issue. Please reach out to https://support.snyk.io for Snyk product questions.

**Comment by zxcv32** [comment]
What does `--skip-unresolved` mean in terms of security?
Does this mean if there are vulnerabilities found in the skipped dependency (which is actively used in the project), we will not be alerted?
