### ISSUE TITLE
[🙏] Make "snyk protect" fast

### ISSUE THREAD

**Issue by ncjones** [snyk/cli#1180]
**Describe the user need**

`snyk protect` needs to be fast and deterministic.

**Describe expected behaviour**

When `snyk protect` runs it should only apply previously-approved patches. It should not perform any source parsing or scanning or discovery of new vulnerabilities. 

**Additional context**

Installing dependencies is the slowest part of most delivery pipelines. A common pattern for speeding up pipeline steps is to have a persistent dependency cache shared between pipelines. When dependencies are already up-to-date then there is basically zero cost to install dependencies granting an enormous speed boost. In my experience this shaves off about 30-60s from any step that runs  `yarn install` on medium-sized nodejs projects and makes it worthwhile to run multiple pipeline steps in parallel which shaves off minutes from the pipeline overall. The poor performance of `snyk protect` undermines all the gains we have made in optimizing our pipeline by adding about 120s to every `yarn install` regardless of whether node_modules were already up-to-date.

**Potential Workaround**

Add a wrapper script that runs `snyk protect` then copies ".snyk" to "node_modules/.snyk-protected" file. The wrapper script can do nothing if the file matches ".snyk".

**Comment by ncjones** [comment]
Example snyk-protect wrapper script:
```bash
#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"
snyk_protected_file=node_modules/.snyk-protected 
touch "${snyk_protected_file}"
if diff .snyk "${snyk_protected_file}" > /dev/null; then
  echo "Snyk patches already applied"
  exit 0
fi
yarn run snyk protect
cp .snyk "${snyk_protected_file}"
```

**Comment by lili2311** [comment]
👋 Hi there, sorry to hear about this slowness 🐌  I would like to share how protect works and then we can see if there is something we can do here.

When ever you run `install` a fresh set of `node_modules` is generated, this means that the downloaded code is unpatched. So the `snyk protect` command will check what patches are meant to be applied from `.snyk` file, download them and find the right `node_module` package path if it can to apply a `patch` that patches the underlying packages *.js code.

So if at any point the node_modules are re-installed, the protect command will have to run again. 

When you say you have the `node_modules` cached, is that the cached `node_modules` *after* all patches are applied? There is a `.snyk-flag` next to each patched module if the path was applied already.

**Comment by jerr0328** [comment]
I'm also seeing similar behavior.

If I re-run `snyk protect` after `yarn install`, it still takes 2 minutes to run, even though `node_modules` was unchanged. I do see a `.snyk-<id>.flag` file, e.g. `node_modules/lodash/.snyk-SNYK-JS-LODASH-567746.flag` in my `node_modules`, but it still seems to be taking a long time to re-apply patches.

**Comment by lili2311** [comment]
hi @jerr0328 are you able to share what patches are being applied? If that is sensitive can you at least confirm if one of them is for lodash?

**Comment by lili2311** [comment]
thanks for confirming @ncjones! Since that is a very popular dep it probably appears many times and we do re-apply a patch if we find a patch flag, will feedback this internally and discuss if there are some improvements we can add.

**Comment by JackuB** [comment]
Snyk protect command was removed from the Snyk CLI and was replaced by a smaller and faster approach. More details in the product announcements: https://updates.snyk.io/snyk-wizard-and-snyk-protect-removal-224137
