### ISSUE TITLE
[🐛] GitHub Snyk bot not removing created new GitHub branch after pull request is approved and merged

### ISSUE THREAD

**Issue by jerrychong25** [snyk/cli#1236]
- `node -v`: N/A
- `npm -v`: N/A
- `snyk -v`: N/A
- OS: macOS
- Command run: N/A

### Expected behaviour
Automatically remove Synk's created branch after GitHub's pull request is approved and merged.

### Actual behaviour
Synk's created branch remain after GitHub's pull request is approved and merged.

### Steps to reproduce

1. Access GitHub repo
2. Wait until Synk's create a new pull request for fixing repo security vulnerabilities
3. Approved the pull request, and wait until merged.
4. Back to GitHub repo main page.
5. Click **branches**.
6. The Synk's created new branch still remain there.

Note: I have merged 5 pull request, therefore have 5 new branch in the screenshot.

### Debug log
N/A

### Screenshots
<img width="1256" alt="Screenshot 2020-06-25 at 9 36 14 AM" src="https://user-images.githubusercontent.com/15714095/85644147-bb481800-b6c8-11ea-9a51-e5a185feda8f.png">

**Comment by JackuB** [comment]
Hey @jerrychong25, you can setup your GitHub project to automatically delete merged branches in settings https://help.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches

And iirc there are GitHub Actions available for more complex setups.

Closing this issue, but feel free to reopen 👍

**Comment by jerrychong25** [comment]
Hi @JackuB ,

I would strongly suggest **Synk** handling this delete branch automatically instead of user manually setting it.

I saw [dependabot](https://dependabot.com/) would delete this branch automatically after their pull request is approved and merged, as per screenshot below:
<img width="940" alt="Screenshot 2020-06-25 at 11 12 50 PM" src="https://user-images.githubusercontent.com/15714095/85747284-bb343080-b739-11ea-859d-8164c568592c.png">

Could advise on this suggestion?

Thanks!

**Comment by jerrychong25** [comment]
Btw, I don't have the privilege to reopen this issue again.

**Comment by JackuB** [comment]
@jerrychong25 Hey, sorry, missed the response and thought anyone may reopen an issue.

I don't think we are planning any changes in the behavior, especially since it's a [configurable behavior on GitHub side](https://help.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches) already. Got any reasons why do you think handling it should be done by our side as well?

**Comment by jerrychong25** [comment]
@JackuB Thanks for opening the issue again.

The valid reason for this:
Since Synk is creating new pull request + new branch for fixing vulnerabilities (Not user behaviour created these branch), so it make sense for Synk to delete these new branch after pull request is merged.

**Comment by jerrychong25** [comment]
Sample Result:
<img width="949" alt="Screenshot 2020-07-19 at 1 46 37 AM" src="https://user-images.githubusercontent.com/15714095/87858617-c9085a80-c961-11ea-8955-f26038593f5b.png">

Reference Url: https://github.com/jerrychong25/node-express-mongo-passport-jwt-typescript/pull/17

**Comment by jfoclpf** [comment]
> Since Synk is creating new pull request + new branch for fixing vulnerabilities (Not user behaviour created these branch), so it make sense for Synk to delete these new branch after pull request is merged.

I fully agree, suddenly I realized I have a huge list of branches from snyk. How the heck do we need a new branch to change a line of code in `package.json`?

**Comment by jerrychong25** [comment]
> > Since Synk is creating new pull request + new branch for fixing vulnerabilities (Not user behaviour created these branch), so it make sense for Synk to delete these new branch after pull request is merged.
> 
> I fully agree, suddenly I realized I have a huge list of branches from snyk. How the heck do we need a new branch to change a line of code in `package.json`?

Yes agreed, faced same issue as well. But it unavoidable on creating batch for pushing new codes.

Just Snyk need to deleted created branch after pull request is accepted.

**Comment by jfoclpf** [comment]
> Just Snyk need to deleted created branch after pull request is accepted.

Exactly, fully agreed!

**Comment by JackuB** [comment]
Closing as it's not relevant to the Snyk CLI. See https://docs.snyk.io for Snyk products documentation
Please reach out to https://support.snyk.io for Snyk product questions.

If anyone still runs into this, as mentioned above there is a GitHub supported option to automatically delete branches after merging: https://help.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches
