### ISSUE TITLE
[🐛] `snyk wizard` runs `snyk monitor` internally with undesirable side effects

### ISSUE THREAD

**Issue by wheresrhys** [snyk/cli#1385]
- `node -v`: v12.18.3
- `npm -v`: 6.14.6
- `snyk -v`: 1.319.0
- OS:  OSX
- Command run: `snyk wizard`

### Expected behaviour
Running `snyk wizard` should fix my project locally and not have any affect on the data available via snyk dashboards. Only my snyk integrations that form part of my deploy pipeline (either using the CLI in CI or using the github integration) should update the snyk dashboards.

### Actual behaviour
Running `snyk wizard` pushes data to snyk
1. As an enterprise customer, this has the undesirable consequence of creating a project in the default org. My team's existing projects are not in the default org, so this creates a duplicate with a conflicting report.
2. Even if that weren't an issue, why would I even _want_ to mark a project's vulnerabilities as fixed when the fix is still only on my local laptop? It doesn't feel like the most sensible behaviour to include in `snyk wizard` by default.

### Steps to reproduce
Run snyk wizard on any project

**Comment by lili2311** [comment]
👋 @wheresrhys I completely agree this does not seem ideal for your usecase when fixing locally and not wanting this to reflect on monitored projects especially if a branch is different.
We have some planned work to see how to support branches better & CI/CLI fix capabilities improvements, there is nothing more concrete that I can share at the moment.

I can advise a way to bypass this somewhat: 
When you scan a project with --json you will get a `remediation` object that suggests which dep to upgrade to which other dep. This can be used to do a manual upgrade of all suggested. (The same information is in the human friendly output when you run snyk test)

We can look into skipping the monitor step with a flag as well, will discuss internally to see if this makes sense to add.

**Comment by wheresrhys** [comment]
Thanks Lili. A flag or - preferably (because people forget to add flags) - interactive question to skip the monitor step would be great.

**Comment by lili2311** [comment]
Yes of course the interactive question much better :)
