### ISSUE TITLE
Known issues with Snyk Wizard command

### ISSUE THREAD

**Issue by JackuB** [snyk/cli#1478]
[The Snyk Wizard command `$ snyk wizard`](https://support.snyk.io/hc/en-us/articles/360000920818-What-is-the-difference-between-snyk-test-protect-and-monitor-) has fallen behind and is in need of a redesign. There are currently multiple issues about Wizard opened, I'll be closing some of them and merging them here.

Known issues and missing features
- Wizard does not show progress
- **Wizard may produce different results than `snyk test`**
- Wizard misses "Apply Previous" option #95
- There isn't an option to disable the [`monitor` command](https://support.snyk.io/hc/en-us/articles/360000920818-What-is-the-difference-between-snyk-test-protect-and-monitor-) when wizard finishes #1385
- Wizard doesn't show patchable issues #1409
- Wizard (or any other command) does not cleanup the `.snyk` file
- General performance and stability issues #445 #404 
- Confusing language when `.snyk` file is already present

There isn't a timeline yet. First, we plan to focus on [Snyk Protect command](https://github.com/snyk/snyk/issues/1477), that has much bigger impact on the npm ecosystem. Feel free to add more suggestions on improving Wizard command to this issue.

**Comment by bmherold** [comment]
Is there any timeline on this? Our company has made Snyk a mandatory component of our security process, and the inability to run and generate .snyk files against our repositories is a serious blocking issue.

**Comment by JackuB** [comment]
Snyk wizard will be removed from the Snyk CLI: https://updates.snyk.io/snyk-wizard-and-snyk-protect-removal-224137
