### ISSUE TITLE
One of the transient npm dependency is missing a LICENSE file 

### ISSUE THREAD

**Issue by char0n** [snyk/cli#182]
The transient dependency in question is: https://www.npmjs.com/package/thunkify, https://github.com/tj/node-thunkify

When snyk installs it installs this transient dependency too. As this dependency doesn't have a license, the entire snyk installation is rouge at this point and cannot be used. Can this be somehow remedied pls ? We can help to remedy this.

cc @miiila

**Comment by adrukh** [comment]
@char0n thanks for reporting this!

`thunkify@2.1.2` is pulled in as a transitive dependency of `proxy-agent@2.3.1`. This package indeed misses a `LICENSE` file, but it is published with an MIT license according to https://github.com/tj/node-thunkify/blob/master/package.json#L12 and the npmjs page.

Can you explain why is this an issue for you?

**Comment by char0n** [comment]
There is only a mention of the name of the license, but there is no license text it self. MIT requires a full license text with copyright notice that is currently missing. Which in legal  world means - there is not license at all and nobody is eligible to use this software. According to MIT every code distribution must be accompanied by the full text of the license with the copyright notice - and this doesn't concern only the github repo but the npm package itself too. The npm package is a form of code distribution and this code is missing license.

I hope it make sense.

**Comment by adrukh** [comment]
Thanks for clarifying!

The proper course of action here would be opening a PR for `thunkify`, introducing the `LICENSE` file.

**Comment by lili2311** [comment]
👋 Is this still an issue for you with latest version of the cli?

**Comment by char0n** [comment]
@opichals you have the tools to verify if this is still an issue or not ;]

**Comment by opichals** [comment]
Yeah, but beware some of the reported issues may be false negatives...

```sh
$ bb dep check snyk
Analyzing the package `snyk@latest` ...
Getting dependencies...
Creating the list of 4th party deps... list.txt
Creating the Public License field contents... licenses.txt

snyk@1.290.2
License: Apache-2.0
Copyright Notice: Copyright 2015 Snyk Ltd.
Dependencies: 308
Eligible for Pre-Approval: False

Description: snyk library and cli utility
Package: https://npmjs.com/package/snyk
Repo: https://github.com/snyk/snyk


Problematic Licenses: 10
@yarnpkg/lockfile@1.1.0 (BSD-2-Clause) - missing copyright notice, missing full license text
event-loop-spinner@1.1.0 (MIT) - missing full license text
invert-kv@1.0.0 (MIT) - missing full license text
is-npm@1.0.0 (MIT) - missing full license text
jszip@3.2.2 (MIT OR GPL-3.0) - license not pre-approved
pako@1.0.11 (MIT AND Zlib) - license not pre-approved
path-is-inside@1.0.2 (WTFPL OR MIT) - license not pre-approved
rc@1.2.8 (BSD-2-Clause OR MIT OR Apache-2.0) - license not pre-approved
set-immediate-shim@1.0.1 (MIT) - missing full license text
thunkify@2.1.2 (MIT) - missing copyright notice

Bad luck! Before adding the dependency to the approval process you need to manually go through the dependencies, get the missing info and complete the generated files with it.

ProTip: You can use --debug to print more details.
```

**Comment by char0n** [comment]
@lili2311 thunkify@2.1.2 is still part of your tree. So code without a proper license is still being installed on people computers.

**Comment by JackuB** [comment]
👋 Snyk CLI is now published without npm dependencies that needs installing, because we are bundling them. Licenses are included in the bundle in a file [`thirdPartyNotice.json`](https://github.com/snyk/cli/blob/6abc83a9bf8a1ff9a24af2e03a168169838f951a/webpack.prod.ts#L14). You can read more about it here: https://updates.snyk.io/smaller-and-faster-cli!-206415 and here https://github.com/snyk/cli/blob/6abc83a9bf8a1ff9a24af2e03a168169838f951a/help/_about-this-project/why-we-are-bundling-dependencies.md
