### ISSUE TITLE
.snyk files are sometimes ignored

### ISSUE THREAD

**Issue by schmod** [snyk/cli#195]
- `snyk -v`: 1.90.2
- Command run: `snyk test`

### Expected behaviour
When I have a `.snyk` file in my module's root directory, I expect `snyk test` to use and respect the rules defined in this file.

### Actual behaviour
Even though `snyk policy` correctly locates and parses the my `.snyk` file, the rules in the file are silently(!) ignored when I run `snyk test`.

### Steps to reproduce
This bug appears to be triggered if my module has a dependency that has `"snyk": true` in its `package.json` file, but does not have its own `.snyk` file (possibly because it wasn't published to NPM).

#### Module `a`
* Sources located in `/source/a` (I run `snyk test` from this directory)
* Has a .snyk file
* Depends on `b`

#### Module `b`
* Has `"snyk": true` in its `package.json`
* Does *not* have `.snyk` included in the bundle published to NPM (ie. `/source/a/node_modules/b/.snyk` does not exist)

---

The relevant code appears in [`lib/snyk-test/npm/index.js`](https://github.com/snyk/snyk/blob/ace19f7394a9500d34bdb2247a6d75e78601cf5a/lib/snyk-test/npm/index.js#L85-L90).

As you can see, `policy.load()` takes a list of potential policy locations, and quietly swallows errors if *any* of the policy files fail to load.  

```js
return snyk.policy.load(policyLocations, options)
  .then(function (policy) {
    payload.body.policy = policy.toString();
    return {
      package: pkg,
      payload: payload,
    };
  }, function (error) { // note: inline catch, to handle error from .load
    // the .snyk file wasn't found, which is fine, so we'll return
    if (error.code === 'ENOENT') {
      return {
        package: pkg,
        payload: payload,
      };
    }
    throw error;
```

Snyk is looking for `.snyk` files in my dependencies because of `"snyk": true`, which is handled in the [`pluckPolicies` function](https://github.com/snyk/snyk/blob/ace19f7394a9500d34bdb2247a6d75e78601cf5a/lib/snyk-test/npm/index.js#L218-L220).  Interestingly, this function does not seem to respect the `--trust-policies` command-line option, and processes the policy files of my dependencies regardless of whether or not I pass in that command-line flag.

Ideally, snyk should:
* Gracefully handle missing `.snyk` files in my dependencies, and print a warning.
* Respect the `--trust-policies` command-line flag.
* Accurately display the policy that will _actually_ be applied by `snyk test `when I run `snyk policy`.

**Comment by lili2311** [comment]
👋 There has been a few changes in this area recently, is the latest CLI version still behaving like this?

To be clear is the bug is that if a dependency has `snyk:true` with no .snyk file we are ignoring the .snyk file in your directory too?

**Comment by lili2311** [comment]
@schmod did you get a chance to re-check?

**Comment by JackuB** [comment]
Closing as it's a stale issue
