### ISSUE TITLE
[🐛] Recommendations for your base image (library/debian:bullseye-slim) are not available.

### ISSUE THREAD

**Issue by mcandre** [snyk/cli#2204]
> Recommendations for your base image (library/debian:bullseye-slim) are not available.

Why come Snyk does not present recommendations for base image layers?

This error message is ambiguous. What action, if any, are users supposed to take to address this?

Does Snyk _ever_ provide recommendations for base images, or is this just a fact of how Snyk always operates?

**Comment by JackuB** [comment]
Please reach out to https://support.snyk.io/ for Snyk product questions, we are not able to support you in GitHub issues.
I think it will help support if you could also share full package.jsons you are trying to scan.

See https://docs.snyk.io/ for Snyk products documentation
