### ISSUE TITLE
[🙏] Bitbucket server - add default reviewers to created PR

### ISSUE THREAD

**Issue by lpandzic** [snyk/cli#2291]
Right now Snyk doesn't add default reviewers when creating PRs on Bitbucket which breaks developer experience. Developers are accustomed to getting notified when someone creates a PR on their project and it's expected of them to review the PR.

Here's the same question on atlassian side - https://community.atlassian.com/t5/Bitbucket-questions/Default-reviewers-on-pull-requests-via-API/qaq-p/1442675 from 2017 where linked answer provides some insight into how fetching/adding default reviewers should be done.

**Comment by alosenkov-infobip** [comment]
The use-case: a repository in BitBucket server has default reviewers on the repository level and it's great if Snyk retrieves this list e.g. like noted here https://community.atlassian.com/t5/Bitbucket-questions/How-to-add-existing-default-reviewers-when-creating-pull-request/qaq-p/627849 and then put them into newly created PR by default.

This is expected behaviour by developers.

**Comment by alosenkov-infobip** [comment]
The problem is still relevant for us.

**Comment by lpandzic** [comment]
@JackuB, how can I request a feature on https://support.snyk.io/ that would also be publicly visible to everyone in the community? How can community vote on most important feature requests?

**Comment by JackuB** [comment]
@lpandzic hey, we don't have a public feature tracker. That said, you should still reach out to the support and discuss your needs, maybe they can help!

**Comment by lpandzic** [comment]
Understood. I just wanted to state that the process is nontransparent and that's really a shame.

**Comment by PikaBlue107** [comment]
Happy follow-up: This issue's feature request has been implemented in the Bitbucket Server integration: https://updates.snyk.io/default-reviewer-assignee-to-pull-requests-in-bitbucket-server-data-center-244725

However, this feature is *currently* still not implemented for the [Bitbucket Cloud Legacy](https://docs.snyk.io/integrations/git-repository-scm-integrations/bitbucket-cloud-legacy-integration#project-monitoring-and-automatic-fix-pull-requests) / [Bitbucket Cloud App](https://docs.snyk.io/integrations/git-repository-scm-integrations/bitbucket-cloud-app-integration#project-level-security-reports) integrations, which makes the "Automatic Fix Pull-Request" feature of both integrations nigh unusable for many folks in my company.

I'm extremely grateful to the Snyk team for improving developer experience by implementing this feature in one integration. However, it's hard to know where to help. I believe @lpandzic's suggestion of a public feature tracker would greatly benefit both your community of users and the Snyk organization itself. I imagine 100 votes on 16 features is *much* easier to track on your side than 100 separate support tickets. Scaling problems within the domain of communication are tricky, but having a public space to discuss these requests helps all of us tackle those problems together. <3
