### ISSUE TITLE
[🐛] error: FailedToRunTestError: self signed certificate

### ISSUE THREAD

**Issue by CNAG-dpico** [snyk/cli#2298]
When I run snyk containter test using --insecure flag to ignore the self signed certificate installed on own docker registry local. It seems the command it is ignoring this flag.

### Steps to reproduce

# snyk container test --insecure registry.local:5000/apptool:1-test -d

### Debug log

snyk analytics {
"args": [
  "registry.local:5000/apptool:1-test",
  {
    "insecure": true,
    "debug": true,
    "docker": true,
    "experimental": true
  }
],
"command": "bad-command",
"metadata": {
  "local": true,
  "error-message": "\nTesting registry.local:5000/apptool:1-test...\n\nself signed certificate",
  "error": "Error: \nTesting registry.local:5000/apptool:1-test...\n\nself signed certificate\n    at test (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/commands/test/index.ts:241:19)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at runCommand (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:57:25)\n    at main (/usr/local/lib/node_modules/snyk/dist/cli/webpack:/snyk/src/cli/index.ts:317:11)",
  "error-code": "DEPTH_ZERO_SELF_SIGNED_CERT",
  "command": "test"
},
"os": "Linux 3.10",
"version": "1.731.0",
"nodeVersion": "v14.18.0",
"standalone": false,
"integrationName": "DOCKER_SNYK_CLI",
"integrationVersion": "docker",
"integrationEnvironment": "",
"integrationEnvironmentVersion": "",
"id": "17e0adcd3cb13f7.....e31f5c9c5d6a8d3",
"ci": false,
"environment": {
  "npmVersion": "6.14.15"
},
"durationMs": 2131,
"metrics": {
  "network_time": {
    "type": "timer",
    "values": [],
    "total": 0
  },
  "cpu_time": {
    "type": "synthetic",
    "values": [
      2131
    ],
    "total": 2131
  }
}
} +0ms
snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
snyk request body size: 1352 +0ms
snyk gzipped request body size: 625 +0ms
snyk not using proxy +1ms

**Comment by SimonGurney** [comment]
bump, this is definitely a thing.  Cannot use snyk to scan harbour images atm when there is a self-signed cert on it.

**Comment by SimonGurney** [comment]
So the fix is to add this ENV variable
`NODE_TLS_REJECT_UNAUTHORIZED = "0" `

Found it on this thread: https://github.com/request/request/issues/418

**Comment by JackuB** [comment]
Closing the issue as it is resolved.
Snyk CLI will be changing handling of these configurations in the future.

**Comment by KyleXSmith** [comment]
This is still an issue for me.
