### ISSUE TITLE
[🐛] snyk/snyk-cli python tags are overridden

### ISSUE THREAD

**Issue by malkam03** [snyk/cli#2335]
Python tags that are uploaded to [the docker hub](https://hub.docker.com/r/snyk/snyk-cli/tags?page=1&name=python) are not being tagged with the cli version but only with the python version making it impossible to choose a python image with an specific snyk cli version.

- `node -v`:
Not relevant
- `npm -v`:
Not relevant
- `snyk -v`:
Not relevant
- OS: (e.g. OSX, Linux, Windows, ...)
Not relevant
- Command run: (e.g. `snyk test --all-projects`, `snyk protect`, ...)
Not relevant

### Expected behavior

To be able to download older versions of the snyk-cli python docker image. For example doing a `docker pull amr-cache-registry.caas.intel.com/cache/snyk/snyk-cli:1.658-python-3`.

### Actual behavior

Only the latest version of the snyk-cli is available with the tag `python-3`.

### Steps to reproduce

Please share _minimal_ steps needed to reproduce your issue. Ideally
a paired down manifest / project to showcase the problem that can also
be used for testing.

### Debug log

N/A

### Screenshots

N/A

**Comment by JackuB** [comment]
Hey, could you expand on why do you need a specific CLI version in such image?

**Comment by malkam03** [comment]
Hi @JackuB, sorry I missed your first comment. Sure the reason is simple. The server our company is using has an specific version installed and IT upgrades it from time to time. But if we upgrade the cli before the server is, then we can see some issues (last time it took us 1 day to debug what was wrong).
