### ISSUE TITLE
[🐛] snyk wizard hangs

### ISSUE THREAD

**Issue by JonHolman** [snyk/cli#2435]
- `node -v`: v14.16.1
- `npm -v`: 7.14.0
- `snyk -v`: 1.720.0
- OS: (e.g. OSX, Linux, Windows, ...) OSX
- Command run: (e.g. `snyk test --all-projects`, `snyk protect`, ...)
snyk wizard

### Expected behaviour

Please share _expected_ behaviour.

### Actual behaviour

% snyk wizard
Snyk's wizard will:

* Enumerate your local dependencies and query Snyk's servers for vulnerabilities
* Guide you through fixing found vulnerabilities
* Create a .snyk policy file to guide snyk commands such as `test` and `protect`
* Remember your dependencies to alert you when new vulnerabilities are disclosed

Analyzing npm dependencies for /Users/xxxxx/demo-notes-app
| Analyzing npm dependencies for demo-notes-app project dir
<--- Last few GCs --->

[28511:0x118008000]   401943 ms: Mark-sweep 3504.3 (4118.6) -> 3498.1 (4118.6) MB, 2321.7 / 0.0 ms  (average mu = 0.078, current mu = 0.009) allocation failure scavenge might not succeed
[28511:0x118008000]   404815 ms: Mark-sweep 3514.1 (4118.6) -> 3507.9 (4118.6) MB, 2844.5 / 0.0 ms  (average mu = 0.041, current mu = 0.010) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1012e4da5 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000a6239 node::Abort() [/usr/local/bin/node]
 3: 0x1000a639f node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1001e9007 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1001e8fa3 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 6: 0x100397e95 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 7: 0x10039995a v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 8: 0x100395029 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x1003928c1 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
10: 0x1003a115a v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x1003a11e1 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
12: 0x100367f70 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/usr/local/bin/node]
13: 0x1005c199d v8::internal::Handle<v8::internal::NameDictionary> v8::internal::BaseNameDictionary<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::New<v8::internal::Isolate>(v8::internal::Isolate*, int, v8::internal::AllocationType, v8::internal::MinimumCapacity) [/usr/local/bin/node]
14: 0x100581e43 v8::internal::JSObject::MigrateToMap(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Map>, int) [/usr/local/bin/node]
15: 0x10059dbff v8::internal::LookupIterator::Delete() [/usr/local/bin/node]
16: 0x100578ed5 v8::internal::JSReceiver::DeleteProperty(v8::internal::LookupIterator*, v8::internal::LanguageMode) [/usr/local/bin/node]
17: 0x1006fbf66 v8::internal::Runtime::DeleteObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::Object>, v8::internal::LanguageMode) [/usr/local/bin/node]
18: 0x100702370 v8::internal::Runtime_DeleteProperty(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
19: 0x100a7a239 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
20: 0x3e9387008625 
zsh: abort      snyk wizard

### Steps to reproduce

git clone https://github.com/serverless-stack/demo-notes-app.git
npm i      
snyk wizard

### Debug log

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

% snyk wizard --debug
  snyk wizard <ref *1> { _: [ [Circular *1] ], debug: true } +0ms
  snyk ~~~~ LIVE RUN ~~~~ +0ms
  snyk sending request to: https://snyk.io/api/v1/verify/token +0ms
  snyk request body size: 46 +0ms
  snyk gzipped request body size: 66 +0ms
  snyk not using proxy +1ms
  snyk not using proxy +310ms
Snyk's wizard will:

* Enumerate your local dependencies and query Snyk's servers for vulnerabilities
* Guide you through fixing found vulnerabilities
* Create a .snyk policy file to guide snyk commands such as `test` and `protect`
* Remember your dependencies to alert you when new vulnerabilities are disclosed

Analyzing npm dependencies for /Users/xxx/demo-notes-app
| Analyzing npm dependencies for demo-notes-app project dir
<--- Last few GCs --->

[30153:0x118008000]   389535 ms: Mark-sweep 3476.8 (4117.6) -> 3470.5 (4117.4) MB, 2572.7 / 0.0 ms  (average mu = 0.121, current mu = 0.009) allocation failure scavenge might not succeed
[30153:0x118008000]   392435 ms: Mark-sweep 3486.5 (4117.4) -> 3480.2 (4117.4) MB, 2875.0 / 0.0 ms  (average mu = 0.065, current mu = 0.009) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1012e4da5 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000a6239 node::Abort() [/usr/local/bin/node]
 3: 0x1000a639f node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1001e9007 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1001e8fa3 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 6: 0x100397e95 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 7: 0x10039995a v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 8: 0x100395029 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x1003928c1 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
10: 0x1003a115a v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x1003a11e1 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
12: 0x100367f70 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/usr/local/bin/node]
13: 0x1005c199d v8::internal::Handle<v8::internal::NameDictionary> v8::internal::BaseNameDictionary<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::New<v8::internal::Isolate>(v8::internal::Isolate*, int, v8::internal::AllocationType, v8::internal::MinimumCapacity) [/usr/local/bin/node]
14: 0x100581e43 v8::internal::JSObject::MigrateToMap(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Map>, int) [/usr/local/bin/node]
15: 0x10059dbff v8::internal::LookupIterator::Delete() [/usr/local/bin/node]
16: 0x100578ed5 v8::internal::JSReceiver::DeleteProperty(v8::internal::LookupIterator*, v8::internal::LanguageMode) [/usr/local/bin/node]
17: 0x1006fbf66 v8::internal::Runtime::DeleteObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::Object>, v8::internal::LanguageMode) [/usr/local/bin/node]
18: 0x100702370 v8::internal::Runtime_DeleteProperty(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
19: 0x100a7a239 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
20: 0x2416270cf098 
zsh: abort      snyk wizard --debug

**Comment by JackuB** [comment]
Snyk wizard will be removed from the Snyk CLI: https://updates.snyk.io/snyk-wizard-and-snyk-protect-removal-224137
