### ISSUE TITLE
[🙏] Allow snyk test/monitor `--exclude` to by unix glob patterns.

### ISSUE THREAD

**Issue by jabaran** [snyk/cli#2503]
- `Language / Project Type:` N/A
- `Package Manager / Build Tool:` N/A

**Describe the user need**
E.g. I want Snyk to scan my X project that uses Y package manager.

I want to be able to exclude files and folders by using syntax common to unix/linux for both `test` and `monitor` actions.

For those unfamiliar with glob syntax here are couple of references [[1](https://www.malikbrowne.com/blog/a-beginners-guide-glob-patterns)], [[2](https://man7.org/linux/man-pages/man3/glob.3.html)].

**Describe expected behaviour**

This would extend the current `--exclude` functionality by allowing globs to be provided

**Additional context**

There is already a popular [glob](https://www.npmjs.com/package/glob) package which could be evaluated.

In my experience globs appear to be a common way for tools to include/exclude and would allow us to DRY up some of our code if we have that consistent experience.

Supporting this would also address https://github.com/snyk/snyk/issues/2437

**Comment by jabaran** [comment]
Support ticket - https://support.snyk.io/hc/en-us/requests/17632

**Comment by JackuB** [comment]
Closing this issue as there is a support ticket already filled.

**Comment by marcindulak** [comment]
Would it be possible to revisit the issue management so the issues reported on github are only closed after being resolved?
