### ISSUE TITLE
[🐛] Yarn v2 support not working

### ISSUE THREAD

**Issue by dmattia** [snyk/cli#2619]
- `node -v`: v14.17.3
- `npm -v`: 6.14.13
- `snyk -v`:1.828.0
- OS: OSX
- Command run: snyk test

### Expected behaviour

Snyk would work with yarn v2 monorepos, and would report issues with the lodash@4.17.0 dependency that I added in a test

### Actual behaviour

Depending on the command run, I either see the command fail, or I see a successful run that does not pick up dependencies used

### Steps to reproduce

To setup a yarn v2 monorepo (run in an empty directory, not under any existing yarn/npm control):

```bash
yarn init -2
cat package.json | jq '.workspaces=["backend"] | .devDependencies.typescript="=4.4.4" | .name="@test/root"' | sponge package.json
mkdir backend && echo '{}' | jq '.name="@test/backend" | .dependencies={"lodash": "=4.17.10"}' > backend/package.json
yarn
```

Trying to test with Snyk using `yarn dlx snyk test --all-projects --strict-out-of-sync=false`:

<img width="578" alt="Screen Shot 2022-01-21 at 3 14 58 PM" src="https://user-images.githubusercontent.com/8922077/150601053-c6ded1b3-9c8e-4e13-ab31-2860e51818f2.png">

Trying to test with Snyk using `yarn dlx snyk test --yarn-workspaces`:

<img width="284" alt="Screen Shot 2022-01-21 at 3 18 35 PM" src="https://user-images.githubusercontent.com/8922077/150601428-633f123c-e974-4a00-8bf0-7344f5083994.png">

Of note, the `snyk-test Found 0 projects from 2 detected manifests +2ms` error when using `-d` is concerning, and in the end no errors are shown, despite `lodash@4.17.10` having plenty of vulns: https://snyk.io/test/npm/lodash/4.17.10

### Debug log

```text
❯ yarn dlx snyk test --yarn-workspaces -d
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 339ms
➤ YN0000: Done in 0s 534ms

  snyk test <ref *1> { _: [ [Circular *1] ], debug: true, yarnWorkspaces: true } +0ms
  snyk-test auto detect manifest files, found 2 [
  '/Users/foo/transcend/test/package.json',
  '/Users/foo/transcend/test/backend/package.json'
] +0ms
  snyk-yarn-workspaces Processing potential Yarn workspaces (2) +0ms
  snyk-yarn-workspaces Processing /Users/foo/transcend/test as a potential Yarn workspace +0ms
  snyk-yarn-workspaces /Users/foo/transcend/test/package.json is not part of any detected workspace, skipping +1ms
  snyk-yarn-workspaces Processing /Users/foo/transcend/test/backend as a potential Yarn workspace +0ms
  snyk-yarn-workspaces /Users/foo/transcend/test/backend/package.json is not part of any detected workspace, skipping +1ms
  snyk-yarn-workspaces No yarn workspaces detected in any of the 2 target files. +0ms
  snyk-test Found 0 projects from 2 detected manifests +3ms



  snyk analytics {
  "args": [
    {
      "debug": true,
      "yarnWorkspaces": true
    }
  ],
  "command": "test",
  "metadata": {
    "upgradable-snyk-protect-paths": 0,
    "local": true,
    "yarnWorkspaces": {
      "scannedProjects": 0,
      "targetFiles": [
        "/Users/foo/transcend/test/package.json",
        "/Users/foo/transcend/test/backend/package.json"
      ],
      "packageManagers": [
        "npm",
        "npm"
      ],
      "ignore": [
        "node_modules"
      ]
    },
    "pluginName": "snyk-nodejs-yarn-workspaces"
  },
  "os": "macOS Catalina",
  "osPlatform": "darwin",
  "osRelease": "19.6.0",
  "osArch": "x64",
  "version": "1.834.0",
  "nodeVersion": "v14.17.3",
  "standalone": false,
  "integrationName": "",
  "integrationVersion": "",
  "integrationEnvironment": "",
  "integrationEnvironmentVersion": "",
  "id": "<redacted>",
  "ci": false,
  "environment": {
    "npmVersion": "6.14.13"
  },
  "durationMs": 1294,
  "metrics": {
    "network_time": {
      "type": "timer",
      "values": [],
      "total": 0
    },
    "cpu_time": {
      "type": "synthetic",
      "values": [
        1294
      ],
      "total": 1294
    }
  }
} +0ms
  snyk sending request to: https://snyk.io/api/v1/analytics/cli +0ms
  snyk request body size: 890 +0ms
  snyk gzipped request body size: 486 +0ms
  snyk not using proxy +1ms
```

### Screenshots

added inline above

**Comment by JackuB** [comment]
Please reach out to https://support.snyk.io for Snyk product questions, we are not able to support you in GitHub issues. 
I think it will help support if you could also share full package.jsons you are trying to scan.

See https://docs.snyk.io for Snyk products documentation

**Comment by dmattia** [comment]
For anyone else using yarn v2 who stumbles upon this, I did open a ticket in support, was told that yarn v2 support is not present, and this issue has been moved to their engineering backlog with no timeline
