### ISSUE TITLE
[🐛]: Snyk CLI Shows Different Results Than Snyk App For Go

### ISSUE THREAD

**Issue by jnikitin-r7** [snyk/cli#2706]
node -v: v12.18.3
npm -v: 6.14.6
snyk -v:1.842.0
OS: OSX
Command run: snyk test

### Issue

Running Snyk CLI for a go lang package shows different results than Snyk App through GitHub.

```
snyk test --all-projects --dependency-depth=100000000 -d
  snyk test {
  _: [ [Circular] ],
  'dependency-depth': '100000000',
  debug: true,
  allProjects: true
} +0ms
  snyk-test auto detect manifest files, found 4 [
  '/Users/<user>/code/backend/src/github.com/<obfuscated1>/<obfuscated2>/go.mod',
  '/Users/<user>/code/backend/src/github.com/<obfuscated1>/<obfuscated2>/vendor/go.etcd.io/bbolt/go.mod',
  '/Users/<user>/code/backend/src/github.com/<obfuscated1>/<obfuscated2>/vendor/go.opencensus.io/go.mod',
  '/Users/<user>/code/backend/src/github.com/<obfuscated1>/<obfuscated2>/vendor/google.golang.org/grpc/go.mod'
] +0ms
  snyk-yarn-workspaces Processing potential Yarn workspaces (4) +0ms
  snyk-yarn-workspaces No yarn workspaces detected in any of the 4 target files. +0ms
  snyk-test Not part of a workspace: /Users/<user>/code/backend/src/github.com/<obfuscated1>/<obfuscated2>go.mod, /Users/<user>/code/backend/src/github.com/<obfuscated1>/<obfuscated2>/vendor/go.etcd.io/bbolt/go.mod, /Users/<user>/code/backend/src/github.com/<obfuscated1>/<obfuscated2>/vendor/go.opencensus.io/go.mod, /Users/<user>/code/backend/src/github.com/<obfuscated1>/<obfuscated2>/vendor/google.golang.org/grpc/go.mod} +0ms

Testing /Users/<obfs>/code/backend/src/github.com/<obfuscated1>/<obfuscated2>...

Organization:      <obfs>-fwb
Package manager:   gomodules
Target file:       go.mod
Project name:      github.com/<obfuscated1>/<obfuscated2>/v2
Open source:       no
Project path:      /Users/<obfs>/code/backend/src/github.com/<obfuscated1>/<obfuscated2>
Licenses:          enabled

✔ Tested 174 dependencies for known issues, no vulnerable paths found.

Next steps:
- Run `snyk monitor` to be notified about new related vulnerabilities.
- Run `snyk test` as part of your CI/test.
```

App shows this:

![image](https://user-images.githubusercontent.com/75641395/152226504-b8940e88-b9bd-4abb-8ece-0ff2402fd18f.png)

### Expected behaviour

Both should show same vulnerabilities.

### Actual behaviour

Snyk App shows vulnerabilities, but Snyk CLI doesn't find any.

I cannot show direct way to reproduce due to private dependencies.

Both local and online have up-to-date code. I tried running with `--file=go.mod` and `--dependency-depth=10000`.

Snyk CLI only sees 4 go.mod files for some reason, but there's a lot more...

```
 '/Users/<user>/code/backend/src/github.com/<obfuscated1>/<obfuscated2>/go.mod',
  '/Users/<user>/code/backend/src/github.com/<obfuscated1>/<obfuscated2>/vendor/go.etcd.io/bbolt/go.mod',
  '/Users/<user>/code/backend/src/github.com/<obfuscated1>/<obfuscated2>/vendor/go.opencensus.io/go.mod',
  '/Users/<user>/code/backend/src/github.com/<obfuscated1>/<obfuscated2>/vendor/google.golang.org/grpc/go.mod'
```

For example, my project directly imports `github.com/openzipkin/zipkin-go v0.2.5`. But it doesn't show it as vulnerable, even though online app shows:

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/75641395/152228994-5e7bb861-dac9-41e3-a881-f342a963af3b.png">

<img width="656" alt="image" src="https://user-images.githubusercontent.com/75641395/152229045-f5851b4d-a579-44d2-945c-e83860e1ac98.png">

**Comment by JackuB** [comment]
@jnikitin-r7 This is an expected behavior. You can read more here: https://support.snyk.io/hc/en-us/articles/360000920998-Why-did-the-Snyk-CLI-discover-different-dependencies-and-vulnerabilities-than-the-integration-in-the-app- and https://support.snyk.io/hc/en-us/articles/360001649458-Mismatch-of-Vulnerabilities-Why-does-the-CLI-show-a-different-number-of-vulnerabilities-than-through-the-Snyk-App-

Closing this issue as team is we are not using GitHub issues.

See https://docs.snyk.io/ for Snyk products documentation
Please reach out to https://support.snyk.io/ for Snyk product questions.
