### ISSUE TITLE
snyk monitor fails because of just one version?!?

### ISSUE THREAD

**Issue by dzwicker** [snyk/cli#2762]
Have tried to reach the snyk support. But.... 

Have made a record of two snyk monitor calls. See files attached! The difference ist just `org.graalvm.sdk:graal-sdk@21.3.1` vs `org.graalvm.sdk:graal-sdk@21.3.0`.

Really?

Error was:

```
{"code":500,"message":"Internal error (reference: 9d5b57d9-befb-45c3-bb64-4838e4ecff55)","userMessage":"Internal error (reference: 9d5b57d9-befb-45c3-bb64-4838e4ecff55)","error":"Internal error (reference: 9d5b57d9-befb-45c3-bb64-4838e4ecff55)","errorRef":"9d5b57d9-befb-45c3-bb64-4838e4ecff55"}

```
 Please help

[Archive.zip](https://github.com/snyk/snyk/files/8082483/Archive.zip)

**Comment by dzwicker** [comment]
support ticket: https://support.snyk.io/hc/en-us/requests/19351?page=1 👎

**Comment by JackuB** [comment]
Closing this issue as there is a support ticket opened already.
