### ISSUE TITLE
Support for Nim, Dart and Lua

### ISSUE THREAD

**Issue by ariv797** [snyk/cli#2767]
Add support for Nim, Dart and Lua! Granted that Nim and Lua aren't that widespread, Dart is a pretty big language (owned by Google). It also has a huge ecosystem in [pub](https://pub.dev) (their package manager). Lua's [LuaRocks](https://luarocks.org/) and Nim's [Nimble](https://nimble.directory/) are relatively small but are growing quite quickly. Support for smaller programming languages is more useful as most of the packages are new with a greater possibility of security bugs

**Comment by JackuB** [comment]
Hi, thanks for the suggestion! We are always looking into adding support for new languages.
Closing this issue as team is we are not using GitHub issues for tracking feature requests.

See https://docs.snyk.io/ for Snyk products documentation
Please reach out to https://support.snyk.io/ for Snyk product questions.
