### ISSUE TITLE
Snyk has encountered a problem

### ISSUE THREAD

**Issue by hazcod** [snyk/cli#2773]
Running the preview extension on latest VS Code on macOS (M1).

![image](https://user-images.githubusercontent.com/5222512/153749982-e1ab068a-bf35-42d5-8741-645cf997ec6e.png)

```
[Info] Starting full scan
[Info] Open Source Security test started.
[Info] Running "/Users/xxx/.vscode/extensions/snyk-security.snyk-vulnerability-scanner-preview-2022.2.805/snyk-macos test /Users/xxx/Source/foo/bar --json".
[Error] Error: Request failed with status code 500
[Error] Open Source Security test failed for "/Users/xxx/Source/foo/bar". Could not detect supported target files in /Users/xxx/Source/foo/bar.
Please see our documentation for supported languages and target files: https://snyk.co/udVgQ and make sure you are in the right directory.
```

I'm running this in a directory containing subdirectories with a helm template, Dockerfiles and Python code.

**Comment by michelkaporin** [comment]
This seems to be an issue with Snyk CLI since running CLI outside of VS Code plugin returns an error. Transferring it to the responsible repo.

**Comment by JackuB** [comment]
@hazcod Please reach out to https://support.snyk.io/ for Snyk product questions, we are not able to support you in GitHub issues.
I think it will help support if you could also share more about the project you are trying to scan.

See https://docs.snyk.io/ for Snyk products documentation
