### ISSUE TITLE
Commit convention awareness

### ISSUE THREAD

**Issue by Berkmann18** [snyk/cli#283]
- `node -v`: v11.0.0
- `npm -v`: 6.4.1
- `snyk -v`: 1.111.1

I've just started using this service and noticed that it was using the Angular convention for commits (`fix: ...`) except for the Ember/JSHint-like PR title (`[Snyk] Fix ...`) and I was wondering if the bot could detect the commit convention used by the repo it's submitting a PR against (assuming there was one) so that it could respect that.
This could be done by either using auto-detection like how dependabot and commit-lint does or by allowing contributors/repo owners to configure that for a given repo.

Would that be doable?

**Comment by JackuB** [comment]
Closing as it's not relevant to the Snyk CLI. Please reach out to support.snyk.io for Snyk product questions.
