### ISSUE TITLE
Unknown version from maven parent dependencyManagement

### ISSUE THREAD

**Issue by julianladisch** [snyk/cli#3027]
Web UI doesn't find artifact version in the dependencyManagement section of the parent pom.xml. CLI does.

Minimal example reproducing the problem: https://github.com/julianladisch/maven-dependencyManagement

Relevant section of the parent pom.xml:

```
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.vertx</groupId>
        <artifactId>vertx-stack-depchain</artifactId>
        <version>4.2.5</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

Relevant section of submodule/pom.xml:
```
  <dependencies>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>
  </dependencies>
```

Relevant output of `maven dependency:tree` for submodule:
```
[INFO] \- com.fasterxml.jackson.core:jackson-databind:jar:2.13.1:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.1:compile
[INFO]    \- com.fasterxml.jackson.core:jackson-core:jar:2.13.1:compile
```

Snyk CLI detects jackson-core 2.13.1 and correctly reports that jackson-databind 2.13.1 is not vulnerable.

Web UI (using "GitHub" or "Monitor public GitHub repos") should give the same result but it detects
```
com.fasterxml.jackson.core:jackson-databind@unknown 
```
and therefore reports 62 issues against older jackson-databind versions.

**Comment by julianladisch** [comment]
Snyk processes this issue as support ticket 20896.

**Comment by JackuB** [comment]
Closing this issue as there is already a Support ticket created.

**Comment by julianladisch** [comment]
![submodule-dependencyManagement](https://user-images.githubusercontent.com/533612/158846698-5b453313-29f3-4d55-9823-dcb6c588386d.png)
