### ISSUE TITLE
Add option to force coloured output

### ISSUE THREAD

**Issue by ChrisLane** [snyk/cli#3051]
It would be useful if Snyk CLI had an option to force coloured output, something like a `--color=always` argument.

**Comment by JackuB** [comment]
> It would be useful

Could you expand on why this is useful?

Also, I believe `FORCE_COLOR=1` already works today thanks to `chalk` package https://github.com/chalk/chalk#supportscolor

**Comment by ChrisLane** [comment]
> > It would be useful
> 
> Could you expand on why this is useful?
> 
> Also, I believe `FORCE_COLOR=1` already works today thanks to `chalk` package https://github.com/chalk/chalk#supportscolor

The feature is useful for users to read `snyk code test` etc. continuous integration logs easier.
Snyk CLI may not be run in an environment that registers ansi colour support but that doesn't mean that the logs won't be shown somewhere that does.

I've added `FORCE_COLOR=1` to my scripts and that's fixed the lack of colours for me in CI, thanks.

**Comment by illnr** [comment]
Also works for me in GitLab CI. Would be nice to have this in some documentation or as a option as OP suggested. :)

**Comment by JackuB** [comment]
We will consider is as a requirement for the future Snyk CLI versions. Thank you!
