### ISSUE TITLE
Allow pull requests to pass CI

### ISSUE THREAD

**Issue by saschanaz** [snyk/cli#345]
Currently the test requires authentication and access to snyk org (by `--org snyk`) so any PRs from external contributors fail. This is bad.

**Comment by Berkmann18** [comment]
I second that, especially when PRs are made by bots which is a bit problematic.

**Comment by Berkmann18** [comment]
@robcresswell no, repos that uses `snyk`.

**Comment by robcresswell** [comment]
@Berkmann18 Those don't need access to the `snyk` org though, this sounds like a different issue.

**Comment by Berkmann18** [comment]
Huh, my bad, didn't noticed this issue was especially about the organisation as opposed to repos of snyk users.

**Comment by lili2311** [comment]
👋 Is this still an issue that needs a fix/resolving? If not please let me know and I will close

**Comment by saschanaz** [comment]
>Is this still an issue that needs a fix/resolving?

package.json still has `--org=snyk` so yes.

**Comment by lili2311** [comment]
I am not sure I fully understand, why is the fact we test the code in this repo against our own `snyk` org on new PRs an issue for you?

Is something happening somewhere? Do you have some errors/logs to share please?

**Comment by adrukh** [comment]
@lili2311 since our api token is a sensitive env var on travis, it is not exposed for forked PRs, making them fail before they even start testing.

**Comment by lili2311** [comment]
So this is for contributions to this repo?

**Comment by adrukh** [comment]
Exactly. It is much easier to contribute to our plugin repos, for example.

I think we should consider dropping the self-test we run here, as the repo is protected with our GitHub integration.

**Comment by lili2311** [comment]
That makes sense!

**Comment by lili2311** [comment]
Just to give an update here: many tests have been reworked to not require any Org, there is still some way to go before the tests can be run anywhere.

**Comment by JackuB** [comment]
Thank you for the interest! I'm closing this issue, as the tests we are running are heavily dependent on specific environments and access to those is obscured through secrets in our CI.

We don't have plans to rely on open source contributors at this point: https://github.com/snyk/cli#contributing
