### ISSUE TITLE
Generate SBOM

### ISSUE THREAD

**Issue by candrews** [snyk/cli#3862]
[Snyk stresses the importance of SBOMs](https://snyk.io/blog/building-sbom-open-source-supply-chain-security/), yet there's no way to get one from `snyk`.

This issue requests the `snyk` cli to gain the ability to output an SBOM.

`snyk` is already very close to being able to generate an SBOM - the `snyk test --print-deps` functionality added in https://github.com/snyk/cli/pull/2255 outputs most (if not all) of the information necessary to generate one.

https://github.com/snyk/cli/blob/4fe18087f31e89205d2e18139392988815270c7b/src/lib/print-deps.ts#L40 gives a plan for moving forward.

A new command, `sbom`, would be added. This command would generate an SBOM, but not scan for vulnerabilities. It would take many of the same arguments as the existing `test` command (for example but not limited to `--all-projects`, `--maven-aggregate-project`, `--fail-fast`, `--detection-depth=8`, `--configuration-matching=`, etc). The command would, by default, print the SBOM to the console. An argument, `--json-file-output`, would permit saving the SBOM to a file.

The CycloneDX JSON format seems like a good format to use for the SBOM. However, SPDX would be fine as well ([Snyk has previously demoed that format](https://github.com/snyk-tech-services/snyk2spdx)).

Enter this request via Snyk Support as well at https://support.snyk.io/hc/en-us/requests/33250

**Comment by rob-trickey** [comment]
As discussed, we unfortunately won't be able to merge this PR, as it conflicts with our internal plans to build out this feature ourselves, that are well underway. We're building SBOM generation as the first standalone CLI module, so it will live in a different repository to this (written in a different language). We're also intending to Open Source this new repo, and we're looking forward to making this functionality generally available later this year.

We're really sorry not to be able to merge this, this decision is definitely not a reflection on the quality of work here. Enabling standalone modules for the CLI is a key project of ours to improve its extensibility, and a lot of our own effort has gone into enabling SBOM generation to work in this way. We're also looking into how we improve our responsiveness to issues raised on our open source projects, as this conversation should have taken place before you wrote any code, and we can only apologise for missing that too.

**Comment by candrews** [comment]
I've made the work from this PR available in my own fork of Snyk: https://www.npmjs.com/package/@candrewsintegralblue/snyk

An example of how to use it is: `npx @candrewsintegralblue/snyk@latest sbom --cyclonedx-json-file-output=app.cdx.json`

That will scan the project found in the current directory and save the resulting CycloneDX sbom `app.cdx.json`.

**Comment by huornlmj** [comment]
Trivy cli can do this

**Comment by j-luong** [comment]
This issue can be closed now, since the CLI now supports [SBOM output](https://docs.snyk.io/snyk-cli/commands/sbom)
