### ISSUE TITLE
Snyk CLI is missing binaries for release v1.1036.0

### ISSUE THREAD

**Issue by nniesen** [snyk/cli#4162]
Synk CLI release v1.1036.0 is missing all binaries
https://github.com/snyk/cli/releases/tag/v1.1036.0

**Comment by MuazOthman** [comment]
This is causing the [setup action](https://github.com/snyk/actions/blob/master/setup/setup_snyk.sh) to fail downloading binaries for latest version.

**Comment by ewhitman-va** [comment]
We reached out to Snyk regarding this issue and they are looking at it now @nniesen

**Comment by denis-tsoi-mox** [comment]
Does anyone have an alternate remediation? 
would like to implement an immediate fix while snyk updates the binaries

**Comment by nniesen** [comment]
> Does anyone have an alternate remediation?
> would like to implement an immediate fix while snyk updates the binaries

We temporarily pinned to v1.1035.0 but YMMV.

**Comment by wpross** [comment]
> Does anyone have an alternate remediation? would like to implement an immediate fix while snyk updates the binaries

I use 

```yaml
    - uses: snyk/actions/setup@master
      id: snyk
      with:
        snyk-version: v1.1035.0
```
until it is fixed. This works for me.

**Comment by karniwl** [comment]
Hey folks, thanks for raising this. We're investigating the issue. We'll update here as well but you can watch the status page here https://status.snyk.io/

**Comment by mschmiedel** [comment]
Would it be possible to remove the latest tag from a broken release in general and add it to the latest working version? Many people script based on the latest tag, if the release is broken, there is no real value for the tag being there...

**Comment by karniwl** [comment]
@mschmiedel and all, the latest release is now working properly. Please let us know if it's working for you 🙏

**Comment by mschmiedel** [comment]
Hi, everything is up and running fine with 1037 now, my idea with removing the latest tag was just a suggestion so you do not have that much pressure to fix a broken release. With 1037 this is not necessary anymore of course...

**Comment by karniwl** [comment]
Thanks for your update @mschmiedel and your suggestion, appreciated!

**Comment by karniwl** [comment]
this issue is resolved with the new release https://github.com/snyk/cli/releases/tag/v1.1037.0 so I'm closing this issue. Please reopen if you encounter any further issue. Thank you all for raising it and for your patience!
