### ISSUE TITLE
Problem with latest version (1.1045.0) trying to install globally npm-cli-login

### ISSUE THREAD

**Issue by javisan81** [snyk/cli#4183]
The latest version snyk@1.1045.0  is causing to fail the installation of npm-cli-login.
If I try to execute this command in my machine of in any of our pipelines, we have this error:

npm install -g npm-cli-login
11:08:40  [2022-10-31T10:08:40.709Z] npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
11:08:43  [2022-10-31T10:08:43.245Z] npm WARN deprecated har-validator@5.1.5: this library is no longer supported
11:08:43  [2022-10-31T10:08:43.245Z] npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
11:08:46  [2022-10-31T10:08:46.522Z] /home/jenkins/.npm-global/bin/npm-cli-login -> /home/jenkins/.npm-global/lib/node_modules/npm-cli-login/bin/npm-cli-login.js
11:08:46  [2022-10-31T10:08:46.522Z] 
11:08:46  [2022-10-31T10:08:46.522Z] > snyk@1.1045.0 postinstall /home/jenkins/.npm-global/lib/node_modules/npm-cli-login/node_modules/snyk
11:08:46  [2022-10-31T10:08:46.522Z] > bash ./scripts/apply-patches.sh
11:08:46  [2022-10-31T10:08:46.522Z] 
11:08:46  [2022-10-31T10:08:46.522Z] bash: ./scripts/apply-patches.sh: No such file or directory
11:08:46  [2022-10-31T10:08:46.522Z] npm ERR! code ELIFECYCLE
11:08:46  [2022-10-31T10:08:46.522Z] npm ERR! syscall spawn
11:08:46  [2022-10-31T10:08:46.522Z] npm ERR! file sh
11:08:46  [2022-10-31T10:08:46.522Z] npm ERR! errno ENOENT
11:08:46  [2022-10-31T10:08:46.522Z] npm ERR! snyk@1.1045.0 postinstall: `bash ./scripts/apply-patches.sh`
11:08:46  [2022-10-31T10:08:46.522Z] npm ERR! spawn ENOENT
11:08:46  [2022-10-31T10:08:46.522Z] npm ERR! 
11:08:46  [2022-10-31T10:08:46.522Z] npm ERR! Failed at the snyk@1.1045.0 postinstall script.
11:08:46  [2022-10-31T10:08:46.522Z] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
11:08:46  [2022-10-31T10:08:46.522Z] 
11:08:46  [2022-10-31T10:08:46.522Z] npm ERR! A complete log of this run can be found in:
11:08:46  [2022-10-31T10:08:46.522Z] npm ERR!     /home/jenkins/.npm/_logs/2022-10-31T10_08_46_134Z-debug.log

I saw that in package.json there were added these two lines some days ago, that could cause this issue:
    "test:smoke": "./scripts/run-smoke-tests-locally.sh",
    "postinstall": "bash ./scripts/apply-patches.sh"
related to this commit: https://github.com/snyk/cli/commit/a2cbec35c381db560441952485c6c83b8bc9727a

**GitHub Issues are not monited by Snyk Support**

**Comment by tony-snoop** [comment]
This is impacting us too as we get the same error:

```
> snyk@1.1045.0 postinstall /usr/local/lib/node_modules/snyk
> bash ./scripts/apply-patches.sh

bash: ./scripts/apply-patches.sh: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! snyk@1.1045.0 postinstall: `bash ./scripts/apply-patches.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the snyk@1.1045.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above
```

Could this be urgently investigating as currently all our CI/CD builds are failing for multiple developers?

**Comment by hangaoke1** [comment]
same error ~!

**Comment by dotboris** [comment]
This error happens when installing the latest version of snyk. `npm-cli-login` pulls on snyk as a "production" dependency and so that's why it's in the chain. I've been able to reproduce this issue by just installing `snyk` directly.

```sh
$ npm install snyk
npm ERR! code 127
npm ERR! path /Users/bbera/oneoff/snyk-postinstall/node_modules/snyk
npm ERR! command failed
npm ERR! command sh -c -- bash ./scripts/apply-patches.sh
npm ERR! bash: ./scripts/apply-patches.sh: No such file or directory

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bbera/.npm/_logs/2022-10-31T12_06_50_056Z-debug-0.log
```

<details>
<summary>Detailed log</summary>

```
0 verbose cli /usr/local/Cellar/node/18.11.0/bin/node /usr/local/bin/npm
1 info using npm@8.19.2
2 info using node@v18.11.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 4ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/bbera/oneoff/snyk-postinstall/.npmrc Completed in 0ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:/Users/bbera/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 2ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 14ms
19 timing npm:load:configload Completed in 14ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm install snyk
23 verbose argv "install" "snyk"
24 timing npm:load:setTitle Completed in 5ms
25 timing config:load:flatten Completed in 2ms
26 timing npm:load:display Completed in 4ms
27 verbose logfile logs-max:10 dir:/Users/bbera/.npm/_logs
28 verbose logfile /Users/bbera/.npm/_logs/2022-10-31T12_06_50_056Z-debug-0.log
29 timing npm:load:logFile Completed in 5ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 29ms
33 timing arborist:ctor Completed in 0ms
34 silly logfile start cleaning logs, removing 2 files
35 timing arborist:ctor Completed in 0ms
36 silly logfile done cleaning log files
37 timing idealTree:init Completed in 12ms
38 timing idealTree:userRequests Completed in 3ms
39 silly idealTree buildDeps
40 silly fetch manifest snyk@*
41 http fetch GET 200 https://registry.npmjs.org/snyk 3661ms (cache updated)
42 silly placeDep ROOT snyk@1.1045.0 OK for:  want: *
43 timing idealTree:#root Completed in 3699ms
44 timing idealTree:node_modules/snyk Completed in 0ms
45 timing idealTree:buildDeps Completed in 3699ms
46 timing idealTree:fixDepFlags Completed in 1ms
47 timing idealTree Completed in 3717ms
48 timing reify:loadTrees Completed in 3717ms
49 timing reify:diffTrees Completed in 1ms
50 silly reify moves {}
51 timing reify:retireShallow Completed in 1ms
52 timing reify:createSparse Completed in 1ms
53 timing reify:loadBundles Completed in 0ms
54 silly audit bulk request { snyk: [ '1.1045.0' ] }
55 silly tarball no local data for snyk@https://registry.npmjs.org/snyk/-/snyk-1.1045.0.tgz. Extracting by manifest.
56 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 191ms
57 timing auditReport:getReport Completed in 193ms
58 silly audit report {}
59 timing auditReport:init Completed in 0ms
60 timing reify:audit Completed in 193ms
61 http fetch GET 200 https://registry.npmjs.org/snyk/-/snyk-1.1045.0.tgz 5811ms (cache miss)
62 timing reifyNode:node_modules/snyk Completed in 5819ms
63 timing reify:unpack Completed in 5820ms
64 timing reify:unretire Completed in 0ms
65 timing build:queue Completed in 5ms
66 timing build:link:node_modules/snyk Completed in 10ms
67 timing build:link Completed in 11ms
68 info run snyk@1.1045.0 postinstall node_modules/snyk bash ./scripts/apply-patches.sh
69 info run snyk@1.1045.0 postinstall { code: 127, signal: null }
70 timing reify:rollback:createSparse Completed in 53ms
71 timing reify:rollback:retireShallow Completed in 0ms
72 timing command:install Completed in 9640ms
73 verbose stack Error: command failed
73 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
73 verbose stack     at ChildProcess.emit (node:events:513:28)
73 verbose stack     at maybeClose (node:internal/child_process:1091:16)
73 verbose stack     at Socket.<anonymous> (node:internal/child_process:449:11)
73 verbose stack     at Socket.emit (node:events:513:28)
73 verbose stack     at Pipe.<anonymous> (node:net:313:12)
74 verbose pkgid snyk@1.1045.0
75 verbose cwd /Users/bbera/oneoff/snyk-postinstall
76 verbose Darwin 21.6.0
77 verbose node v18.11.0
78 verbose npm  v8.19.2
79 error code 127
80 error path /Users/bbera/oneoff/snyk-postinstall/node_modules/snyk
81 error command failed
82 error command sh -c -- bash ./scripts/apply-patches.sh
83 error bash: ./scripts/apply-patches.sh: No such file or directory
84 verbose exit 127
85 timing npm Completed in 9858ms
86 verbose unfinished npm timer reify 1667218010271
87 verbose unfinished npm timer reify:build 1667218019822
88 verbose unfinished npm timer build 1667218019822
89 verbose unfinished npm timer build:deps 1667218019822
90 verbose unfinished npm timer build:run:postinstall 1667218019838
91 verbose unfinished npm timer build:run:postinstall:node_modules/snyk 1667218019838
92 verbose code 127
93 error A complete log of this run can be found in:
93 error     /Users/bbera/.npm/_logs/2022-10-31T12_06_50_056Z-debug-0.log
```

</details>

I've done some digging and I believe that this issue comes from the following PR: https://github.com/snyk/cli/pull/4105 I'm guessing that the postinstall script doesn't get packaged in the NPM package and that's why it's not found. Note that the script in question does exist in this repo: https://github.com/snyk/cli/blob/master/scripts/apply-patches.sh

My gut tells me that this script is likely to cause problems on platforms that don't have `bash` like Windows or very small linux installations that rely on `sh` instead.

**Comment by dotboris** [comment]
I see a few solutions here to quickly unblock most people:
- Revert https://github.com/snyk/cli/pull/4105 and release. The feature is lost but everyone who's CI depends on this is now unblocked
- Yank `1.1045.0` from NPM. This will unblock most people but any new release will re-introduce the problem
- Add `scripts/apply-patches.sh` to the NPM package. and release that. This will fix the issue for people on platforms with `bash` installed. That's not a full fix but it unblocks most linux / mac users.

**Comment by hangaoke1** [comment]
you can add pre version to you project
```sh
npm i  snyk@1.1044.0 -D 
```

**Comment by Avishagp** [comment]
We are aware of this issue and are working on fixing it. Thank you for flagging!

**Comment by joelgarrett** [comment]
Also seeing this issue in AWS CodeBuild using pnpm:

```
[Container] 2022/10/31 13:45:31 Running command npm install -g pnpm snyk
--
40 | npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
41 | npm ERR! code 127
42 | npm ERR! path /usr/local/lib/node_modules/snyk
43 | npm ERR! command failed
44 | npm ERR! command sh -c bash ./scripts/apply-patches.sh
45 | npm ERR! bash: ./scripts/apply-patches.sh: No such file or directory
46 |  
47 | npm ERR! A complete log of this run can be found in:
48 | npm ERR!     /root/.npm/_logs/2022-10-31T13_45_31_419Z-debug-0.log
49 |  
50 | [Container] 2022/10/31 13:45:32 Command did not exit successfully npm install -g pnpm snyk exit status 127
51 | [Container] 2022/10/31 13:45:32 Phase complete: INSTALL State: FAILED
52 | [Container] 2022/10/31 13:45:32 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm install -g pnpm snyk. Reason: exit status 127
```

**Comment by tony-snoop** [comment]
A big thank you to @danlucian, @Avishagp and @xzhou-snyk for investigating and getting a fix out so promptly.

A newer version of the synk package (1.1046.0) is now available on https://www.npmjs.com/package/snyk.

Testing it out locally now no longer errors.

```bash
$ npm install snyk

added 1 package in 11s
```

**Comment by PeterSchafer** [comment]
Thanks @tony-snoop for the feedback. 
I was just about to respond here. I will close this issue now.  If you feel it needs to be re-opened, please let us know.

Thanks everyone for raising this issue and apologies for the inconvenience!
