### ISSUE TITLE
npm test does not understand package-lock version 3

### ISSUE THREAD

**Issue by sseide** [snyk/cli#4364]
I have a project with a newer package-lock.json v3 file. running "snyk test" exits with error not being able to scan my dependencies:
```
$ snyk test
Dependency config was not found in package-lock.json. Your package.json and package-lock.json are probably out of sync. Please run "npm install" and try again.
```
Version 3 lock files only contain the "packages" key with full path to the packages from within the project folder (e.g. "node_modules/@babel/core/node_modules/debug") but not the top level "dependencies" key anymore with optional (additional) ""dependencies" inside package definition where needed.

As now v3 lockfiles will become more common Snyk scanner should be updated to understand the "packages" structure too to allow dependency analysis as it is AFAIK nearly impossible to regenerate v2 files once there is a v3 one. At least i do not know a way...

```
$ snyk -v
1.1088.0
$ npm -v
8.19.3
$ node -v
v16.19.0
```

**Comment by khassel** [comment]
same here, using `node:lts-alpine` docker image for running `snyk test` which does not work anymore.

At the time writing this `node:lts-alpine` contains

```bash
/workspace # snyk test
Dependency flightradar24-client was not found in package-lock.json. Your package.json and package-lock.json are probably out of sync. Please run "npm install" and try again.
/workspace # node -v
v18.14.0
/workspace # npm -v
9.3.1
/workspace #
```

**Comment by sbmelvin** [comment]
It appears Snyk doesn't support package-lock.json v3. I workaround this issue by using `npm install --lockfile-version=2`.

**Comment by 0m4r** [comment]
I have experienced the same.
`snyk test` run against a package-lock.json version 3 runs without reporting any problem, the same code but with a package-lock.json version 2 is said to have problems.

this happens with and without `--strict-out-of-sync=false` (which is said to be a workaround for the out-of-sync package-lock.json) but there is actually a more significant issue here of not reporting problems.

**Comment by 0m4r** [comment]
> It appears Snyk doesn't support package-lock.json v3. I workaround this issue by using `npm install --lockfile-version=2`.

to make it easier, you can also add an `.npmrc` file to your base folder and add a `lockfile-version=2` line, so that you do not need to specify it in the command line.

**Comment by corinnaSchultz** [comment]
I've been getting very confusing error messages like the following:
```
FATAL: Snyk Security scan failed.
java.lang.RuntimeException: An error occurred. Dependency @moebius/http-graceful-shutdown was not found in package-lock.json. Your package.json and package-lock.json are probably out of sync. Please run "npm install" and try again.
```

When I implemented the suggestion to specify the lockfile-version in an .npmrc file, the error was resolved.

**Comment by dev-trilobyte** [comment]
Checked with current version and it is not working with v3 lockfiles it seems.
`package.json` has pinned vulnerable nunjuck@3.2.3, same version in v3 lockfile but nothing reported.
There should be this one at least: https://security.snyk.io/vuln/SNYK-JS-NUNJUCKS-5431309

Snyk just outputs
```
Dependency fsevents@~2.3.2 was not found in package-lock.json. Your package.json and package-lock.json are probably out of sync. 
Please run "npm install" and try again.
```
