### ISSUE TITLE
Problem with latest version (1.1102.0) trying to install globally npm-cli-login

### ISSUE THREAD

**Issue by gramcha** [snyk/cli#4406]
root@18e71ef14bb2:~/ubuntu-node-nginx# npm install -g npm-cli-login@1.0.0
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
/usr/bin/npm-cli-login -> /usr/lib/node_modules/npm-cli-login/bin/npm-cli-login.js

> snyk@1.1102.0 postinstall /usr/lib/node_modules/npm-cli-login/node_modules/snyk
> node dist/bootstrap.js exec

Downloading from 'https://static.snyk.io/cli/v1.1102.0/snyk-linux-arm64' to '/usr/lib/node_modules/npm-cli-login/node_modules/snyk/dist/snyk-linux-arm64'
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/usr/lib/node_modules/npm-cli-login/node_modules/snyk/dist/1676307172023'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:335:14
    at FSReqCallback.oncomplete (fs.js:180:23) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/lib/node_modules/npm-cli-login/node_modules/snyk/dist/1676307172023'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snyk@1.1102.0 postinstall: `node dist/bootstrap.js exec`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snyk@1.1102.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-02-13T16_52_52_160Z-debug.log

**Comment by claudinoac** [comment]
https://github.com/postmanlabs/npm-cli-login/issues/83

**Comment by jg75** [comment]
It looks like 1.1103.0 was published right after 1.1102.0, but same error.

Downloading from 'https://static.snyk.io/cli/v1.1103.0/snyk-linux' to '/usr/local/lib/node_modules/npm-cli-login/node_modules/snyk/dist/snyk-linux'
--
74 | events.js:377
75 | throw er; // Unhandled 'error' event
76 | ^
77 |  
78 | Error: EACCES: permission denied, open '/usr/local/lib/node_modules/npm-cli-login/node_modules/snyk/dist/1676317675289'
79 | Emitted 'error' event on WriteStream instance at:
80 | at internal/fs/streams.js:335:14
81 | at FSReqCallback.oncomplete (fs.js:180:23) {
82 | errno: -13,
83 | code: 'EACCES',
84 | syscall: 'open',
85 | path: '/usr/local/lib/node_modules/npm-cli-login/node_modules/snyk/dist/1676317675289'
86 | }
87 | npm ERR! code ELIFECYCLE
88 | npm ERR! errno 1
89 | npm ERR! snyk@1.1103.0 postinstall: `node dist/bootstrap.js exec`
90 | npm ERR! Exit status 1
91 | npm ERR!
92 | npm ERR! Failed at the snyk@1.1103.0 postinstall script.
93 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
94 |  
95 | npm ERR! A complete log of this run can be found in:
96 | npm ERR!     /root/.npm/_logs/2023-02-13T19_47_55_588Z-debug.log

**Comment by xumeng** [comment]
Same error, Anyone is dealing this error?

**Comment by PeterSchafer** [comment]
Hello everyone,

Thank you for raising this issue with us. We are currently investigating reported installation issues via npm. 

We know that some of these issues are related to the use of NPM <= 6 and the installation as root user, these cases could  be solved by either using `--unsafe-perm` during the installation or by upgrading NPM >= 7.

If this doesn't help, a temporary fix would be, to pin to version 1.1100.0 via npm or [use standalone binaries of the CLI](https://docs.snyk.io/snyk-cli/install-the-snyk-cli#install-with-standalone-executables).

We are sorry for the inconvenience and will update here as soon as possible.

**Comment by PeterSchafer** [comment]
FYI we have rolled back the changes we made to the NPM deployment to investigate further. I will therefore close this issue.
