### ISSUE TITLE
Oops! Your sleazy sales team member Julian Lockwood has spammed me 🤬

### ISSUE THREAD

**Issue by andyshinn** [snyk/cli#4456]
Your sales team is harvesting emails and trolling LinkedIn to spam domains. Really sad. Snyk looks like a decent product. If its use ever comes up in my organization and I cannot stop progress moving forward then I will at least do everything in my power to make sure Julian Lockwood gets zero credit.

**Comment by rdegges** [comment]
Hey Andy -- after checking around internally, it looks like we sent you one cold outreach email. We certainly didn't mean to spam you, and apologize for rubbing you the wrong way. Wishing you the best of luck with your security programs.
