### ISSUE TITLE
Feature Request: Automate policy updating

### ISSUE THREAD

**Issue by lad475** [snyk/cli#455]
Our organization uses Snyk, and we find ourselves having to update our policy very frequently in order to prevent our builds from failing- it can get tedious after a while, and so I was wondering if a flag can be created to pick the recommended resolution to each vulnerability automatically in order to automate the process.

The flag could be added onto `snyk wizard` as a flag like `--fix` or `--fix-recommended`.  It would be great to be able to add something like this to our build process in order to automate fixing vulnerabilities.

**Comment by yuliabaron** [comment]
Hi,

Are you using "Enable automatic pull requests for all projects in this organisation" option?  It will allow us to automatically open Fix PRs when a vulnerability is identified

**Comment by lili2311** [comment]
@lad475 👋 Could you please share a little but more about `having to update our policy very frequently`. What kind of updates to you do often here?

When you say `--fix` are you referring to auto applying the `wizard suggestions`?
