### ISSUE TITLE
snyk test not working with Python 3.10.6

### ISSUE THREAD

**Issue by SashaShcherbyna** [snyk/cli#4602]
OS: Ubuntu22.04
snyk --version: 1.1156.0

### Steps to reproduce:
python -m venv snyk_venv
pip install -r requirements.txt
snyk test --debug  --command=snyk_venv/bin/python3

### Debug log:
```
snyk:run-test Error running test {
  error: REQUIRED_PACKAGES_MISSING_ERROR: Required packages missing: importlib-resources

  Please run `pip install -r requirements.txt`. If the issue persists try again with --skip-unresolved.
      at /snapshot/snyk/dist/cli/webpack:/snyk/node_modules/snyk-python-plugin/dist/dependencies/inspect-implementation.js:145:1
      at Generator.throw (<anonymous>)
      at rejected (/snapshot/snyk/dist/cli/webpack:/snyk/node_modules/tslib/tslib.es6.js:73:33)
}
```

**Comment by timothybonci** [comment]
I'm facing a similar issue - I think I have more details.  It looks like the requirements parsing doesn't respect env_var declarations in setup.cfg files for dependencies.

I'm using Python 3.10.11 and Snyk CLI 1.1156.0
My requirements.txt includes
`aiohttp==3.8.4`
The setup.cfg for that package contains:
```install_requires =
  charset-normalizer >=2.0, < 4.0
  multidict >=4.5, < 7.0
  async_timeout >= 4.0, < 5.0
  asynctest == 0.13.0; python_version<"3.8"
  yarl >= 1.0, < 2.0
  typing_extensions >= 3.7.4; python_version<"3.8"
  frozenlist >= 1.1.1
  aiosignal >= 1.1.2```
  
The error I get in my snyk monitor run says "ERROR: Required packages missing: asynctest"
This is a bug, since that is only a requirement if my environment shows python < 3.8

**Comment by timothybonci** [comment]
Found this article suggesting downgrading to 1.1152.0 https://support.snyk.io/hc/en-us/articles/11016357999133?input_string=python+requirements+incorrectly+flagged+as+missing

**Comment by timothybonci** [comment]
It looks like the Python package rolled back the likely breaking change and published [v1.25.2](https://github.com/snyk/snyk-python-plugin/releases/tag/v1.25.2)  This was put as the new floor in 1.1158.0 released today.  I'll try updating to that.

**Comment by SashaShcherbyna** [comment]
Version: 1.1159.0
works fine

**Comment by mangin** [comment]
By the way it was the source of the problem:
https://github.com/snyk/snyk-python-plugin/blob/v1.25.1/pysrc/pkg_resources/_vendor/packaging/markers.py#L267

```py
x = platform.python_version()
print(x) # 3.10.1
print(platform.python_version()[:3])
# 3.1
```
