### ISSUE TITLE
Failed to load and create WASM plugin on macOS

### ISSUE THREAD

**Issue by marcus-sa** [snyk/cli#5005]
When trying to use the Snyk CLI after a clean installation on macOS using brew or npm I get the following error:
```
Error: plugin::create::failed

  × Failed to load and create WASM plugin: Xp�  �{�`�D� @տ`@տ`��J�
  ╰─▶ Xp�       �{�`�D� @տ`@տ`��J�
```

**Comment by thisislawatts** [comment]
Thanks for the report @marcus-sa, please can I ask that you make a report via [Contact Snyk Support on the web](http://support.snyk.io) or email us at support@snyk.io
