### ISSUE TITLE
Yarn workspace packages with past security issues are checked against the wrong version

### ISSUE THREAD

**Issue by Rugvip** [snyk/cli#5009]
We're running this issue in https://github.com/backstage/backstage, where some of our published package have had vulnerabilities that have since been fixed.

The issue is that we are still getting reports of these vulnerabilities from other packages in the workspace that depend on the original package using a `workspace:` dependency version range. This seems to be because the Snyk CLI grabs the version from `yarn.lock`, which will be the placeholder `0.0.0-use.local`, and rather than looking up the local version it uses it as the actual version.

This can be reproduced as follows:

- Clone https://github.com/backstage/backstage
- In the root of the project, run `yarn snyk:test --sarif-file-output=snyk.sarif`
- Verify the presence of `SNYK-JS-BACKSTAGEPLUGINSCAFFOLDERBACKEND-5730767` in `snyk.sarif`. This vulnerabilities has been fixed by `@backstage/plugin-scaffolder-backend` version `1.15.0`, and no older versions of that package are present in the repo, yet vulnerability is still listed.

**Comment by thisislawatts** [comment]
Thanks for the report @Rugvip, please can I ask that you make a report via [Contact Snyk Support on the web](http://support.snyk.io/) or email us at [support@snyk.io](mailto:support@snyk.io)
