### ISSUE TITLE
Provide Typescript Binding for main Snyk entrypoint(s)

### ISSUE THREAD

**Issue by jessehouwing** [snyk/cli#60]
It'd be nice if Typescript would procve a Typescript binding so it's easy to integrate Snyk in Typescript based solutions. This would allow the integrator to call snyk directly, without having to shell out to the commandline.

**Comment by JackuB** [comment]
This is on a long-term roadmap, closing this issue as we are not using GitHub Issues for tracking feature requests.

Thank you!
