### ISSUE TITLE
Remove extraneous ignore entries in .snyk file

### ISSUE THREAD

**Issue by zypA13510** [snyk/cli#741]
- `node -v`: v10.16.3
- `npm -v`: 6.9.0
- `snyk -v`: 1.127.3
- Command run: snyk wizard
<details><summary>(click to expand)</summary>

```console
$ npx snyk wizard
Snyk's wizard will:

  * Enumerate your local dependencies and query Snyk's servers for vulnerabilities
  * Guide you through fixing found vulnerabilities
  * Create a .snyk policy file to guide snyk commands such as `test` and `protect`
  * Remember your dependencies to alert you when new vulnerabilities are disclosed

? Existing .snyk policy found. Ignore it and start from scratch [y] or update it
 [N]? No
Analyzing npm dependencies for /home/***
Analyzing npm dependencies for *** project dir
Querying vulnerabilities database...
✓ Tested 182 dependencies for known vulnerabilities, no vulnerable paths found.
? Add `snyk test` to package.json file to fail test on newly disclosed vulnerabi
lities?
This will require authentication via `snyk auth` when running tests. No
Saving .snyk policy file...
Remembering current dependencies for future notifications...

Your .snyk policy file has been successfully updated.
To review your policy, run `snyk policy`.

You can see a snapshot of your dependencies here:
https://snyk.io/org/***

We'll notify you when relevant new vulnerabilities are disclosed.

$ npx snyk policy
Current Snyk policy, read from .snyk file
Modified: ***
Created:  ***

#1 Ignore https://snyk.io/vuln/SNYK-JS-SEQUELIZE-174167 in the following paths:
sequelize
Reason: ***
Expires: ***

$ npm ls sequelize
***@*** /home/***
└── sequelize@4.44.3 
```
</details>

### Expected behaviour
Since [SNYK-JS-SEQUELIZE-174167](https://snyk.io/vuln/SNYK-JS-SEQUELIZE-174167) only affects sequelize >=5.0.0, the current installation is not affected. This ignore rule is useless now and snyk should remove it automatically when updating .snyk file.

### Actual behaviour
This rule is not removed.

### Steps to reproduce
1. Ignore a vulnerability when it was considered to affect your installation (I remember SNYK-JS-SEQUELIZE-174167 was incorrectly marked as affecting <5.3.0 in the past)
2. Change the vulnerability's affected range so that the installation is no longer affected (in this case, >=5.0.0 <5.3.0)
3. Run `snyk wizard` to update policy file.

**Comment by orkamara** [comment]
Hi @zypA13510 - Thanks for opening this ticket :)
Is that issue blocks you from using Snyk? or a recommendation for improving the functionality?

**Comment by zypA13510** [comment]
@orkamara It's not a critical block, just an inconvenience. You can consider it a feature/enhancement proposal.

**Comment by orkamara** [comment]
Thanks @zypA13510 - I know that in the near future the team that owns this component suppose to do some major improvements, and I guess this will be part of those changes :)

**Comment by GuiSim** [comment]
We'd love to see superfluous ignore entries removed automatically (or perhaps through a specific CLI operation)!

Has there been any progress on this feature request since August 2019?

**Comment by lili2311** [comment]
👋 When you run `snyk wizard` you have an option to start the `.snyk` file again. Does this cover your use case here? Are you looking for for something to automatically remove *old* ignores? At what stage/when do you think this would be appropriate?

**Comment by GuiSim** [comment]
@lili2311 > Are you looking for for something to automatically remove old ignores?
Yep!

The use case is this:
- We have a security vulnerability detected by snyk due to library X. There is no fix yet.
- We add a ignore for this vulnerability and snooze it for 1 month.
- 1 month later, we see that there is a fix available. We update library X.

We now want to "refresh" our snyk ignores, removing all ignores that don't cover any vulnerabilities that are active in our codebase. Essentially removing all ignores that at this point serve no purpose.

I hope that makes sense!

**Comment by jzarnett** [comment]
> 👋 When you run `snyk wizard` you have an option to start the `.snyk` file again. 

Unfortunately for our projects, we cannot use Snyk wizard because "Snyk wizard for Gradle projects is not currently supported"

**Comment by lili2311** [comment]
@jzarnett it is true Gradle is not supported, wizard currently relies on using the underline tools to run some kind of install command. I would appreciate it if you can share what kind of expected updates do you expect to see here? 

For example if we recommend to upgrade:
-  *direct* dep A@1 to a@2, what changes do you expect to see?
- *transitive* dep B@1 to B@2, what changes do you expect to see?

What is your standard process to manually update a dependency? This information will really help us understand what different users expect from Gradle remediation.

**Comment by jzarnett** [comment]
The standard process for updating a dependency involves making a change in a `.gradle` file where some library version is set from A@1 -> A@2 (which will also affect transitive dependencies). 

A gradle remediation where we could use the wizard would be cool but I think that's beyond the scope of this request. 

What I am imagining is more along the lines of a CLI option `snyk cleanup` (name the command whatever makes the most sense) that goes through the `.snyk` file and removes the ignore directives that have expiration dates in the past.

**Comment by JackuB** [comment]
Cleanup of .snyk file is currently a known missing feature. We currently don't have plans to implement a solution to this. Closing this issue as team is we are not using GitHub issues for tracking feature requests.

See https://docs.snyk.io for Snyk products documentation
Please reach out to https://support.snyk.io for Snyk product questions.
